# Generated by Django 6.1.1 on 2026-09-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_alter_garden_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
