# Generated by Django 6.1.1 on 2026-09-09 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gardens.plant'),
        ),
    ]
